declare module 'lucide-react-native' {
  import React from 'react';
  import { SvgProps } from 'react-native-svg';

  export interface IconProps extends SvgProps {
    color?: string;
    size?: number | string;
    strokeWidth?: number | string;
  }

  export const Icon: React.FC<IconProps>;
  export const Award: React.FC<IconProps>;
  export const Sparkles: React.FC<IconProps>;
  export const TrendingUp: React.FC<IconProps>;
  export const Flame: React.FC<IconProps>;
  export const Zap: React.FC<IconProps>;
  export const BookOpen: React.FC<IconProps>;
  export const Code: React.FC<IconProps>;
  export const Cpu: React.FC<IconProps>;
  export const CheckCircle: React.FC<IconProps>;
  export const Play: React.FC<IconProps>;
  export const Pause: React.FC<IconProps>;
  export const RotateCcw: React.FC<IconProps>;
  export const ChevronRight: React.FC<IconProps>;
  export const ChevronLeft: React.FC<IconProps>;
  export const Lock: React.FC<IconProps>;
  export const Check: React.FC<IconProps>;
  export const User: React.FC<IconProps>;
  export const Settings: React.FC<IconProps>;
  export const Home: React.FC<IconProps>;
  export const Compass: React.FC<IconProps>;
  export const Bot: React.FC<IconProps>;
  export const Swords: React.FC<IconProps>;
  export const BarChart2: React.FC<IconProps>;
  export const Share2: React.FC<IconProps>;
  export const ArrowLeft: React.FC<IconProps>;
  export const HelpCircle: React.FC<IconProps>;
  export const LogOut: React.FC<IconProps>;
  export const Shield: React.FC<IconProps>;
  export const Bell: React.FC<IconProps>;
  export const Copy: React.FC<IconProps>;
  export const RefreshCw: React.FC<IconProps>;
  export const Send: React.FC<IconProps>;
  export const Target: React.FC<IconProps>;
  export const Star: React.FC<IconProps>;
  export const Trophy: React.FC<IconProps>;
  export const Brain: React.FC<IconProps>;
  export const Network: React.FC<IconProps>;
  export const Grid: React.FC<IconProps>;
  export const Activity: React.FC<IconProps>;
  export const Layers: React.FC<IconProps>;
  export const GitBranch: React.FC<IconProps>;
  export const Database: React.FC<IconProps>;
  export const Terminal: React.FC<IconProps>;
  export const Search: React.FC<IconProps>;
  export const ListFilter: React.FC<IconProps>;
  export const ArrowUpDown: React.FC<IconProps>;
  export const Info: React.FC<IconProps>;
  export const X: React.FC<IconProps>;
  export const BrainCircuit: React.FC<IconProps>;
  export const MessageCircle: React.FC<IconProps>;
  export const Heart: React.FC<IconProps>;
  export const PlayCircle: React.FC<IconProps>;
  export const Rows3: React.FC<IconProps>;
  export const Sigma: React.FC<IconProps>;
  export const SquareStack: React.FC<IconProps>;
  export const Trees: React.FC<IconProps>;
  export const ArrowRight: React.FC<IconProps>;
  export const Lightbulb: React.FC<IconProps>;
  export const LoaderCircle: React.FC<IconProps>;
  export const Briefcase: React.FC<IconProps>;
  export const ChevronDown: React.FC<IconProps>;
  export const ChevronUp: React.FC<IconProps>;
  export const ListChecks: React.FC<IconProps>;
  export const ThumbsDown: React.FC<IconProps>;
  export const ThumbsUp: React.FC<IconProps>;
  export const Volume2: React.FC<IconProps>;
  export const CheckCircle2: React.FC<IconProps>;
  export const XCircle: React.FC<IconProps>;
  export const Upload: React.FC<IconProps>;
  export const UploadCloud: React.FC<IconProps>;
  export const AlertCircle: React.FC<IconProps>;
  export const AlertTriangle: React.FC<IconProps>;
  export const FileText: React.FC<IconProps>;
  export const FileSpreadsheet: React.FC<IconProps>;
  export const FileCode: React.FC<IconProps>;
  export const Download: React.FC<IconProps>;
  export const ExternalLink: React.FC<IconProps>;
  export const Video: React.FC<IconProps>;
  export const Eye: React.FC<IconProps>;
  export const EyeOff: React.FC<IconProps>;
  export const Mail: React.FC<IconProps>;
  export const ShieldCheck: React.FC<IconProps>;

  const LucideIcon: React.FC<IconProps>;
  export default LucideIcon;
}
