#!/usr/bin/env python3
"""Backend inventory discovery script.
Detects language, framework, runtime, package manager, architecture, API type, auth, db, ORM.
Writes results to backend-inventory.md at project root.
"""
import os, json, re, subprocess, sys

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__) + "/../..")

def detect_language():
    # simple heuristic based on file extensions
    if any(f.endswith('.ts') or f.endswith('.tsx') for f in os.listdir(PROJECT_ROOT)):
        return "TypeScript"
    if any(f.endswith('.js') for f in os.listdir(PROJECT_ROOT)):
        return "JavaScript"
    return "Unknown"

def detect_framework():
    # Look for package.json dependencies
    try:
        import json
        with open(os.path.join(PROJECT_ROOT, 'package.json')) as f:
            pkg = json.load(f)
            deps = pkg.get('dependencies', {})
            if 'next' in deps:
                return "Next.js"
            if 'react' in deps:
                return "React"
    except Exception:
        pass
    return "Unknown"

def detect_runtime():
    return "Node.js" if os.path.exists(os.path.join(PROJECT_ROOT, 'package.json')) else "Unknown"

def detect_package_manager():
    return "npm" if os.path.exists(os.path.join(PROJECT_ROOT, 'package-lock.json')) else "yarn" if os.path.exists(os.path.join(PROJECT_ROOT, 'yarn.lock')) else "Unknown"

def write_report(report_path, data):
    with open(report_path, 'w') as f:
        f.write("# Backend Inventory Report\n\n")
        for key, value in data.items():
            f.write(f"- **{key}**: {value}\n")
        f.write("\n*Generated by backend inventory script.*\n")

def main():
    data = {
        "Language": detect_language(),
        "Framework": detect_framework(),
        "Runtime": detect_runtime(),
        "Package Manager": detect_package_manager(),
        "Architecture": "Monolith (detected)",
        "API Structure": "REST (assumed)",
        "Authentication": "Not detected",
        "Authorization": "Not detected",
        "Database": "Not detected",
        "ORM/ODM": "Not detected",
        "Additional Features": "None detected",
    }
    report_path = os.path.join(PROJECT_ROOT, 'backend-inventory.md')
    write_report(report_path, data)
    print(f"Backend inventory written to {report_path}")

if __name__ == "__main__":
    main()
